// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'Objects/ObjectBox/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(3, 1028974137047872354),
      name: 'Party',
      lastPropertyId: const IdUid(3, 3535150075065647455),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6091705255038676174),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8502944687515635134),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3535150075065647455),
            name: 'tableId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 3216641991569362167),
            relationTarget: 'myTable')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 7639733328394587700),
      name: 'myTable',
      lastPropertyId: const IdUid(2, 7913464457750292665),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3591896250182657774),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7913464457750292665),
            name: 'tableNumber',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(5, 7639733328394587700),
      lastIndexId: const IdUid(2, 3216641991569362167),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [
        9070991375759217764,
        6541336931039621162,
        9056045383993088491
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8123659760592865178,
        4339627968343728224,
        4804298527816204121,
        860247414556252008,
        3873068093839183365,
        8396402611567574263,
        7467828056380379891
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Party: EntityDefinition<Party>(
        model: _entities[0],
        toOneRelations: (Party object) => [object.table],
        toManyRelations: (Party object) => {},
        getId: (Party object) => object.id,
        setId: (Party object, int id) {
          object.id = id;
        },
        objectToFB: (Party object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.table.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Party(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          object.table.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.table.attach(store);
          return object;
        }),
    myTable: EntityDefinition<myTable>(
        model: _entities[1],
        toOneRelations: (myTable object) => [],
        toManyRelations: (myTable object) => {},
        getId: (myTable object) => object.id,
        setId: (myTable object, int id) {
          object.id = id;
        },
        objectToFB: (myTable object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.tableNumber);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = myTable(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Party] entity fields to define ObjectBox queries.
class Party_ {
  /// see [Party.id]
  static final id = QueryIntegerProperty<Party>(_entities[0].properties[0]);

  /// see [Party.name]
  static final name = QueryStringProperty<Party>(_entities[0].properties[1]);

  /// see [Party.table]
  static final table =
      QueryRelationToOne<Party, myTable>(_entities[0].properties[2]);
}

/// [myTable] entity fields to define ObjectBox queries.
class myTable_ {
  /// see [myTable.id]
  static final id = QueryIntegerProperty<myTable>(_entities[1].properties[0]);

  /// see [myTable.tableNumber]
  static final tableNumber =
      QueryIntegerProperty<myTable>(_entities[1].properties[1]);
}
